// <auto-generated />
namespace CarsStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Model16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model16));
        
        string IMigrationMetadata.Id
        {
            get { return "202004201425476_Model16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
